CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  uid TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS products (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  "discountPercent" NUMERIC DEFAULT 0,
  category TEXT DEFAULT 'tshirt',
  colors TEXT[] DEFAULT ARRAY['Black', 'Blue'],
  sizes TEXT[] DEFAULT ARRAY['S', 'M', 'L', 'XL'],
  image TEXT DEFAULT '',
  description TEXT DEFAULT '',
  "userId" TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
